# Generated by Django 4.2.23 on 2026-04-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0005_rename_country_climate_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='climate_type',
            field=models.CharField(choices=[('Temperature', '°C'), ('Precipitation', 'mm'), ('Relative Humidity', '%'), ('Wind Speed', 'm/s'), ('Wind Direction', '°'), ('Atmospheric Pressure', 'hPa'), ('Cloud Cover', '%'), ('Solar Radiation', 'MJ/m²'), ('Visibility', 'm'), ('Soil Moisture', 'm³/m³'), ('Evapotranspiration', 'mm'), ('Dew Point', '°C'), ('UV Index', '')], help_text='i.e. Temperature, Precipitation', max_length=100),
        ),
        migrations.AlterField(
            model_name='climate',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='climate',
            name='unit_standardized',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
